In [15]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# np.add()

In [2]:
# np.add() adds two arrays element-wise
np.add(a ,b)

array([ 6,  8, 10, 12])

# np.max()

In [3]:
# np.max(): finds the maximum of two arrays element-wise
np.max(a)

4

# np.min()

In [6]:
# np.min(): finds the minimum of two arrays element-wise
np.min(b)

5

# np.sqrt()

In [7]:
# np.sqrt(): computes the square root of each element in the input array
np.sqrt(b)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712])

# np.exp()

In [9]:
# np.exp() computes the exponential of each element in the input array
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# np.exp()

In [18]:
# np.exp() computes the exponential of each element in the input array
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# np.log()

In [19]:
# np.log() computes the natural logarithm of each element in the input array
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

# np.sin()

In [17]:
# np.sin() computes the sine of each element in the input array
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# np.cos()

In [20]:
#  np.cos() computes the cosine of each element in the input array
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# np.tan()

In [22]:
#  np.tan() computes the tangent of each element in the input array
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])